import i0 from "../covers/pictures/0.jpg";
import i1 from "../covers/pictures/1.jpg";
import i2 from "../covers/pictures/2.jpg";
import i3 from "../covers/pictures/3.jpg";
import i4 from "../covers/pictures/4.jpg";
import i5 from "../covers/pictures/5.jpg";
import i6 from "../covers/pictures/6.jpg";
import i7 from "../covers/pictures/7.jpg";
import i8 from "../covers/pictures/8.jpg";
import i9 from "../covers/pictures/9.jpg";
import i10 from "../covers/pictures/10.jpg";
import i11 from "../covers/pictures/11.jpg";
import i12 from "../covers/pictures/12.jpg";
import i13 from "../covers/pictures/13.jpg";
import i14 from "../covers/pictures/14.jpg";
import i15 from "../covers/pictures/15.jpg";
import i16 from "../covers/pictures/16.jpg";
import i17 from "../covers/pictures/17.jpg";
import i18 from "../covers/pictures/18.jpg";
import i19 from "../covers/pictures/19.jpg";
import i20 from "../covers/pictures/20.jpg";
import i21 from "../covers/pictures/21.jpg";
import i22 from "../covers/pictures/22.jpg";
import i23 from "../covers/pictures/23.jpg";
import i24 from "../covers/pictures/24.jpg";
import i25 from "../covers/pictures/25.jpg";
import i26 from "../covers/pictures/26.jpg";
import i27 from "../covers/pictures/27.jpg";
import i28 from "../covers/pictures/28.jpg";
import i29 from "../covers/pictures/29.jpg";
import i30 from "../covers/pictures/30.jpg";
import i31 from "../covers/pictures/31.jpg";
import i32 from "../covers/pictures/32.jpg";
import i33 from "../covers/pictures/33.jpg";
import i34 from "../covers/pictures/34.jpg";
import i35 from "../covers/pictures/35.jpg";
import i36 from "../covers/pictures/36.jpg";
import i37 from "../covers/pictures/37.jpg";
import i38 from "../covers/pictures/38.jpg";
import i39 from "../covers/pictures/39.jpg";
import i40 from "../covers/pictures/40.jpg";
import i41 from "../covers/pictures/41.jpg";
import i42 from "../covers/pictures/42.jpg";
import i43 from "../covers/pictures/43.jpg";
import i44 from "../covers/pictures/44.jpg";
import i45 from "../covers/pictures/45.jpg";
import i46 from "../covers/pictures/46.jpg";
import i47 from "../covers/pictures/47.jpg";
import i48 from "../covers/pictures/48.jpg";
import i49 from "../covers/pictures/49.jpg";
import i50 from "../covers/pictures/50.jpg";
import i51 from "../covers/pictures/51.jpg";
import i52 from "../covers/pictures/52.jpg";
import i53 from "../covers/pictures/53.jpg";
import i54 from "../covers/pictures/54.jpg";
import i55 from "../covers/pictures/55.jpg";
import i56 from "../covers/pictures/56.jpg";
import i57 from "../covers/pictures/57.jpg";
import i58 from "../covers/pictures/58.jpg";
import i59 from "../covers/pictures/59.jpg";
import i60 from "../covers/pictures/60.jpg";
import i61 from "../covers/pictures/61.jpg";
import i62 from "../covers/pictures/62.jpg";
import i63 from "../covers/pictures/63.jpg";
import i64 from "../covers/pictures/64.jpg";
import i65 from "../covers/pictures/65.jpg";
import i66 from "../covers/pictures/66.jpg";
import i67 from "../covers/pictures/67.jpg";
import i68 from "../covers/pictures/68.jpg";
import i69 from "../covers/pictures/69.jpg";
import i70 from "../covers/pictures/70.jpg";
import i71 from "../covers/pictures/71.jpg";
import i72 from "../covers/pictures/72.jpg";
import i73 from "../covers/pictures/73.jpg";
import i74 from "../covers/pictures/74.jpg";
import i75 from "../covers/pictures/75.jpg";
import i76 from "../covers/pictures/76.jpg";
import i77 from "../covers/pictures/77.jpg";
import i78 from "../covers/pictures/78.jpg";
import i79 from "../covers/pictures/79.jpg";
import i80 from "../covers/pictures/80.jpg";
import i81 from "../covers/pictures/81.jpg";
import i82 from "../covers/pictures/82.jpg";
import i83 from "../covers/pictures/83.jpg";
import i84 from "../covers/pictures/84.jpg";
import i85 from "../covers/pictures/85.jpg";
import i86 from "../covers/pictures/86.jpg";
import i87 from "../covers/pictures/87.jpg";
import i88 from "../covers/pictures/88.jpg";
import i89 from "../covers/pictures/89.jpg";
import i90 from "../covers/pictures/90.jpg";
import i91 from "../covers/pictures/91.jpg";
import i92 from "../covers/pictures/92.jpg";
import i93 from "../covers/pictures/93.jpg";
import i94 from "../covers/pictures/94.jpg";
import i95 from "../covers/pictures/95.jpg";
import i96 from "../covers/pictures/96.jpg";
import i97 from "../covers/pictures/97.jpg";
import i98 from "../covers/pictures/98.jpg";
import i99 from "../covers/pictures/99.jpg";
import i100 from "../covers/pictures/100.jpg";
import i101 from "../covers/pictures/101.jpg";
import i102 from "../covers/pictures/102.jpg";
import i103 from "../covers/pictures/103.jpg";
import i104 from "../covers/pictures/104.jpg";
import i105 from "../covers/pictures/105.jpg";
import i106 from "../covers/pictures/106.jpg";
import i107 from "../covers/pictures/107.jpg";
import i108 from "../covers/pictures/108.jpg";
import i109 from "../covers/pictures/109.jpg";
import i110 from "../covers/pictures/110.jpg";
import i111 from "../covers/pictures/111.jpg";
import i112 from "../covers/pictures/112.jpg";
import i113 from "../covers/pictures/113.jpg";
import i114 from "../covers/pictures/114.jpg";
import i115 from "../covers/pictures/115.jpg";
import i116 from "../covers/pictures/116.jpg";
import i117 from "../covers/pictures/117.jpg";
import i118 from "../covers/pictures/118.jpg";
import i119 from "../covers/pictures/119.jpg";
import i120 from "../covers/pictures/120.jpg";

const images = [
  { image: i0 },
  { image: i1 },
  { image: i2 },
  { image: i3 },
  { image: i4 },
  { image: i5 },
  { image: i6 },
  { image: i7 },
  { image: i8 },
  { image: i9 },
  { image: i10 },
  { image: i11 },
  { image: i12 },
  { image: i13 },
  { image: i14 },
  { image: i15 },
  { image: i16 },
  { image: i17 },
  { image: i18 },
  { image: i19 },
  { image: i20 },
  { image: i21 },
  { image: i22 },
  { image: i23 },
  { image: i24 },
  { image: i25 },
  { image: i26 },
  { image: i27 },
  { image: i28 },
  { image: i29 },
  { image: i30 },
  { image: i31 },
  { image: i32 },
  { image: i33 },
  { image: i34 },
  { image: i35 },
  { image: i36 },
  { image: i37 },
  { image: i38 },
  { image: i39 },
  { image: i40 },
  { image: i41 },
  { image: i42 },
  { image: i43 },
  { image: i44 },
  { image: i45 },
  { image: i46 },
  { image: i47 },
  { image: i48 },
  { image: i49 },
  { image: i50 },
  { image: i51 },
  { image: i52 },
  { image: i53 },
  { image: i54 },
  { image: i55 },
  { image: i56 },
  { image: i57 },
  { image: i58 },
  { image: i59 },
  { image: i60 },
  { image: i61 },
  { image: i62 },
  { image: i63 },
  { image: i64 },
  { image: i65 },
  { image: i66 },
  { image: i67 },
  { image: i68 },
  { image: i69 },
  { image: i70 },
  { image: i71 },
  { image: i72 },
  { image: i73 },
  { image: i74 },
  { image: i75 },
  { image: i76 },
  { image: i77 },
  { image: i78 },
  { image: i79 },
  { image: i80 },
  { image: i81 },
  { image: i82 },
  { image: i83 },
  { image: i84 },
  { image: i85 },
  { image: i86 },
  { image: i87 },
  { image: i88 },
  { image: i89 },
  { image: i90 },
  { image: i91 },
  { image: i92 },
  { image: i93 },
  { image: i94 },
  { image: i95 },
  { image: i96 },
  { image: i97 },
  { image: i98 },
  { image: i99 },
  { image: i100 },
  { image: i101 },
  { image: i102 },
  { image: i103 },
  { image: i104 },
  { image: i105 },
  { image: i106 },
  { image: i107 },
  { image: i108 },
  { image: i109 },
  { image: i110 },
  { image: i111 },
  { image: i112 },
  { image: i113 },
  { image: i114 },
  { image: i115 },
  { image: i116 },
  { image: i117 },
  { image: i118 },
  { image: i119 },
  { image: i120 },
];

export default images;
